[build]
builder = "nixpacks"
buildCommand = "cd backend && python3.11 -m pip install -r requirements.txt"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
